version: '3.3'
services:
  ol-jenkins:
   build: ./ol-jenkins
   ports:
      - "8080:8080"
      - "50000:50000"
  flask-api:
   build: ./flask-api
   ports:
      - "5000:5000"
      - "8000:8000"
   volumes:
      - ../data:/data
   env_file:
      - ../envs/flask-api.env
   depends_on:
      - redis
      - flask-worker
  grafana:
   image: grafana/grafana
   ports:
      - 3000:3000
   depends_on:
      - prometheus
   volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  flask-worker:
   build: ./rq-worker
   depends_on:
      - redis
   volumes:
      - ../data:/data
   env_file:
      - ../envs/flask-worker.env
  redis:
   image: redis
   ports:
      - "6379:6379" 
  prometheus:
   image: prom/prometheus:latest
   ports:
      - "9090:9090"
   volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  redis-exporter:
   image: oliver006/redis_exporter
   ports:
      - "9121:9121"
   env_file:
      - ../envs/redis-exporter.env
