apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: inttest1
  labels:
    app: nfs-client
spec:
  containers:
  - name: nfs-client
    image: docker.io/gra3m3/nfstest:4
    volumeMounts:
    - name: pvc-inttest1
      mountPath: "/inttest1"
  volumes:
     - name: pvc-inttest1
       persistentVolumeClaim:
           claimName: inttest1-pvc
