apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: inttest1
  labels:
    app: nfs-client
spec:
  containers:
  - name: nfs-client
    image: docker.io/gra3m3/nfstest:6
    volumeMounts:
    - name: pvc-inttest3
      mountPath: "/inttest3"
  volumes:
     - name: pvc-inttest3
       persistentVolumeClaim:
           claimName: inttest3-pvc
