apiVersion: v1
kind: PersistentVolume
metadata:
  name: name
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  mountOptions:
  - vers=4
  nfs:
    path: /vol/n4n8_mgmt_sp_storefront_uat
    server: pn8-st-nfilem01.mgmt.msci.org
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
