apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-inttest1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.67
    path: "/nfs/k8s/inttest1"
