apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: name
  namespace: namespace
spec:
  volumeName: volumename
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
