apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: ieng-pv-manager
  name: ieng-pv-manager
  namespace: jarvis
  selfLink: /apis/apps/v1/namespaces/jarvis/deployments/ieng-pv-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ieng-pv-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ieng-pv-manager
    spec:
      containers:
      - image: docker.io/gra3m3/pvc-api:20
        imagePullPolicy: IfNotPresent
        name: ieng-pv-manager
      serviceAccountName: ieng-pv-provisioner
