---

Classification:
  classes:
    - profile::docker::msccdockerhost

mgmt::ssh::server_options:AllowGroups:
    - M_DRAG_Solutions_AM
    - M_DRAG_Service_x_esg
    - M_DRAG_Service_tomcat

exclusions:
  classes:
    - profile::firewall::clear

profile::mscidockerhost::hosttype: "development"
