apiVersion: v1
kind: Service
metadata:
  labels:
    run: ieng-pv-manager
  name: ieng-pv-manager
  namespace: jarvis
  selfLink: /api/v1/namespaces/jarvis/services/ieng-pv-manager
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
    nodePort: 32000
  selector:
    run: ieng-pv-manager
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
